"""Configuration, palette loading, and file watching for OmarchyWriter.

OmarchyWriter owns only ``~/.config/omarchywriter``. When configured to
follow Omarchy (the default), it reads Omarchy's generated current-theme file
and never edits Omarchy configuration, themes, or state.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import re
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib

from omarchywriter.colors_defaults import DARK_COLORS, LIGHT_COLORS
from omarchywriter.paths import AppPaths
from omarchywriter.watcher import FileWatcher

CONFIG_NAME = "config.toml"
COLOR_NAME = "colors.toml"


def get_config_dir() -> Path:
    return AppPaths.from_environment().config_dir


def get_state_dir() -> Path:
    return AppPaths.from_environment().state_dir


def get_config_path() -> Path:
    return AppPaths.from_environment().config


def get_colors_path() -> Path:
    return AppPaths.from_environment().custom_colors


def get_omarchy_colors_path() -> Path:
    """Read-only palette generated by the active Omarchy theme."""
    return AppPaths.from_environment().omarchy_colors


@dataclass
class EditorConfig:
    font: str = "Iosevka"
    font_size: int = 12
    line_spacing: float = 1.2
    tab_width: int = 4
    show_line_numbers: bool = True
    word_wrap: bool = False
    paragraph_spacing: int = 0
    cursor_width: int = 2


@dataclass
class GUIConfig:
    font: str = "Iosevka"
    font_size: int = 9
    window_width: int = 1100
    window_height: int = 700
    show_status_bar: bool = True
    show_tab_bar: bool = False
    center_on_screen: bool = True


@dataclass
class BehaviorConfig:
    auto_save: bool = True
    auto_save_interval: int = 5
    confirm_quit: bool = True


@dataclass
class ThemeConfig:
    source: str = "omarchy"  # "omarchy" or "custom"
    mode: str = "auto"  # "auto", "dark", or "light"


def _section(data: dict[str, Any], name: str) -> dict[str, Any]:
    value = data.get(name, {})
    return value if isinstance(value, dict) else {}


@dataclass
class Config:
    editor: EditorConfig = field(default_factory=EditorConfig)
    gui: GUIConfig = field(default_factory=GUIConfig)
    behavior: BehaviorConfig = field(default_factory=BehaviorConfig)
    theme: ThemeConfig = field(default_factory=ThemeConfig)

    @classmethod
    def from_toml(cls, path: Path) -> "Config":
        if not path.exists():
            return cls()
        with path.open("rb") as config_file:
            data = tomllib.load(config_file)
        if not isinstance(data, dict):
            raise ValueError("config root must be a TOML table")
        editor, gui = _section(data, "editor"), _section(data, "gui")
        behavior, theme = _section(data, "behavior"), _section(data, "theme")
        return cls(
            editor=EditorConfig(
                font=str(editor.get("font", "Iosevka")),
                font_size=int(editor.get("font_size", 12)),
                line_spacing=float(editor.get("line_spacing", 1.2)),
                tab_width=int(editor.get("tab_width", 4)),
                show_line_numbers=bool(editor.get("show_line_numbers", True)),
                word_wrap=bool(editor.get("word_wrap", False)),
                paragraph_spacing=int(editor.get("paragraph_spacing", 0)),
                cursor_width=int(editor.get("cursor_width", 2)),
            ),
            gui=GUIConfig(
                font=str(gui.get("font", "Iosevka")),
                font_size=int(gui.get("font_size", 9)),
                window_width=int(gui.get("window_width", 1100)),
                window_height=int(gui.get("window_height", 700)),
                show_status_bar=bool(gui.get("show_status_bar", True)),
                show_tab_bar=bool(gui.get("show_tab_bar", False)),
                center_on_screen=bool(gui.get("center_on_screen", True)),
            ),
            behavior=BehaviorConfig(
                auto_save=bool(behavior.get("auto_save", True)),
                auto_save_interval=max(1, int(behavior.get("auto_save_interval", 5))),
                confirm_quit=bool(behavior.get("confirm_quit", True)),
            ),
            theme=ThemeConfig(
                source=str(theme.get("source", "omarchy")).lower(),
                mode=str(theme.get("mode", "auto")).lower(),
            ),
        )


@dataclass
class ColorPalette:
    bg: str = "#1a1b1e"
    fg: str = "#d4d4d4"
    cursor: str = "#569cd6"
    selection: str = "#264f78"
    line_number: str = "#808080"
    current_line: str = "#2a2b2e"
    markdown_heading: str = "#e6c384"
    markdown_code: str = "#9cdcfe"
    markdown_quote: str = "#6a9955"
    markdown_link: str = "#569cd6"
    markdown_list: str = "#ce9178"
    markdown_hr: str = "#808080"
    status_bg: str = "#1a1b1e"
    status_fg: str = "#808080"

    @classmethod
    def from_dict(cls, data: dict[str, Any], fallback: dict[str, str]) -> "ColorPalette":
        return cls(**{key: str(data.get(key, fallback[key])) for key in fallback})


@dataclass
class ColorSet:
    dark: ColorPalette = field(default_factory=lambda: ColorPalette.from_dict(DARK_COLORS, DARK_COLORS))
    light: ColorPalette = field(default_factory=lambda: ColorPalette.from_dict(LIGHT_COLORS, LIGHT_COLORS))
    mode: str = "dark"

    @classmethod
    def from_toml(cls, path: Path) -> "ColorSet":
        if not path.exists():
            return cls()
        with path.open("rb") as color_file:
            data = tomllib.load(color_file)
        if not isinstance(data, dict):
            raise ValueError("color root must be a TOML table")
        return cls(
            dark=ColorPalette.from_dict(_section(data, "dark"), DARK_COLORS),
            light=ColorPalette.from_dict(_section(data, "light"), LIGHT_COLORS),
            mode=str(data.get("mode", "dark")).lower(),
        )


def _omarchy_palette(data: dict[str, Any], fallback: dict[str, str]) -> ColorPalette:
    """Map Omarchy semantic color names to the writer palette."""
    color = lambda name, default: str(data.get(name, default))
    background = color("background", fallback["bg"])
    accent = color("accent", fallback["cursor"])
    muted = color("muted", fallback["line_number"])
    return ColorPalette(
        bg=background,
        fg=color("foreground", fallback["fg"]),
        cursor=accent,
        selection=color("selection", fallback["selection"]),
        line_number=color("dark_foreground", muted),
        current_line=color("lighter_background", color("dark_background", fallback["current_line"])),
        markdown_heading=color("yellow", accent),
        markdown_code=color("cyan", accent),
        markdown_quote=color("green", accent),
        markdown_link=color("blue", accent),
        markdown_list=color("orange", accent),
        markdown_hr=muted,
        status_bg=color("dark_background", background),
        status_fg=color("light_foreground", muted),
    )


def load_omarchy_colors(path: Path | None = None) -> ColorSet:
    path = path or get_omarchy_colors_path()
    if not path.exists():
        return ColorSet()
    with path.open("rb") as color_file:
        data = tomllib.load(color_file)
    if not isinstance(data, dict):
        raise ValueError("Omarchy color root must be a TOML table")
    mode = str(data.get("mode", "dark")).lower()
    fallback = LIGHT_COLORS if mode == "light" else DARK_COLORS
    palette = _omarchy_palette(data, fallback)
    return ColorSet(dark=palette, light=palette, mode=mode)


CONFIG_DEFAULTS = '''# ═══ OmarchyWriter config ═══
# Generated by OmarchyWriter. Edit freely — the app hot-reloads on save.

[editor]
font = "Iosevka"
font_size = 12
line_spacing = 1.2
tab_width = 4
show_line_numbers = true
word_wrap = false
paragraph_spacing = 0
cursor_width = 2

[gui]
font = "Iosevka"
font_size = 9
window_width = 1100
window_height = 700
show_status_bar = true
show_tab_bar = false
center_on_screen = true

[behavior]
auto_save = true
auto_save_interval = 5
confirm_quit = true

# Optional theme settings. These are read even when left out of this file.
# [theme]
# "omarchy" reads the active Omarchy palette without changing Omarchy files.
# source = "omarchy"
# For custom palettes: "auto", "dark", or "light".
# mode = "auto"

# ─── Colors ───────────────────────────────────────────────────
# These map to the [dark] section inside colors.toml.
# config.toml does NOT contain colors itself — see colors.toml.
'''

# Values from the pre-1.1 generated config. They are used only when a user's
# existing file still contains the old generated value; personal edits remain
# untouched during the upgrade.
_LEGACY_DEFAULT_REPLACEMENTS = (
    ("editor", "font_size", "14", "12"),
    ("editor", "show_line_numbers", "false", "true"),
    ("editor", "word_wrap", "true", "false"),
    ("gui", "font_size", "12", "9"),
    ("gui", "window_width", "900", "1100"),
    ("behavior", "auto_save", "false", "true"),
)


def _replace_legacy_value(text: str, section: str, key: str, old: str, new: str) -> str:
    """Replace one untouched legacy default while preserving formatting/comments."""
    section_pattern = re.compile(
        rf"(?ms)^\[{re.escape(section)}\][ \t]*\n(?P<body>.*?)(?=^\[|\Z)"
    )
    section_match = section_pattern.search(text)
    if section_match is None:
        return text

    body = section_match.group("body")
    value_pattern = re.compile(
        rf"(?m)^(?P<prefix>[ \t]*{re.escape(key)}[ \t]*=[ \t]*)"
        rf"{re.escape(old)}(?P<suffix>[ \t]*(?:#.*)?$)"
    )
    updated_body = value_pattern.sub(rf"\g<prefix>{new}\g<suffix>", body, count=1)
    return text[: section_match.start("body")] + updated_body + text[section_match.end("body") :]


def _add_missing_tab_setting(text: str) -> str:
    """Add the 1.1 GUI key without replacing an existing user setting."""
    section_pattern = re.compile(r"(?ms)^\[gui\][ \t]*\n(?P<body>.*?)(?=^\[|\Z)")
    section_match = section_pattern.search(text)
    if section_match is None:
        separator = "" if text.endswith("\n") else "\n"
        return f"{text}{separator}\n[gui]\nshow_tab_bar = false\n"

    body = section_match.group("body")
    if re.search(r"(?m)^[ \t]*show_tab_bar[ \t]*=", body):
        return text
    status_pattern = re.compile(r"(?m)^(?P<line>[ \t]*show_status_bar[ \t]*=[^\n]*(?:\n|$))")
    if status_pattern.search(body):
        updated_body = status_pattern.sub(r"\g<line>show_tab_bar = false\n", body, count=1)
    else:
        updated_body = f"{body}show_tab_bar = false\n"
    return text[: section_match.start("body")] + updated_body + text[section_match.end("body") :]


def _migrate_existing_config(cfg_path: Path) -> None:
    """Upgrade old generated defaults without overwriting intentional settings."""
    try:
        original = cfg_path.read_text(encoding="utf-8")
        # Do not rewrite a file that is temporarily invalid while being edited.
        tomllib.loads(original)
    except (OSError, ValueError):
        return

    updated = original
    for section, key, old, new in _LEGACY_DEFAULT_REPLACEMENTS:
        updated = _replace_legacy_value(updated, section, key, old, new)
    updated = _add_missing_tab_setting(updated)
    if updated != original:
        cfg_path.write_text(updated, encoding="utf-8")

COLOR_DEFAULTS = '''# Used only when theme.source = "custom".

[dark]
bg = "#1a1b1e"
fg = "#d4d4d4"
cursor = "#569cd6"
selection = "#264f78"
line_number = "#808080"
current_line = "#2a2b2e"
markdown_heading = "#e6c384"
markdown_code = "#9cdcfe"
markdown_quote = "#6a9955"
markdown_link = "#569cd6"
markdown_list = "#ce9178"
markdown_hr = "#808080"
status_bg = "#1a1b1e"
status_fg = "#808080"

[light]
bg = "#ffffff"
fg = "#1a1b1e"
cursor = "#000000"
selection = "#cce5ff"
line_number = "#808080"
current_line = "#f0f0f0"
markdown_heading = "#0000aa"
markdown_code = "#4444cc"
markdown_quote = "#4a7a3a"
markdown_link = "#0000aa"
markdown_list = "#aa4400"
markdown_hr = "#808080"
status_bg = "#ffffff"
status_fg = "#666666"
'''


def init_user_config(cfg_path: Path | None = None, clr_path: Path | None = None) -> None:
    """Create the app's files and safely migrate old generated config values."""
    cfg_path, clr_path = cfg_path or get_config_path(), clr_path or get_colors_path()
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    if not cfg_path.exists():
        cfg_path.write_text(CONFIG_DEFAULTS, encoding="utf-8")
    else:
        _migrate_existing_config(cfg_path)
    if not clr_path.exists():
        clr_path.write_text(COLOR_DEFAULTS, encoding="utf-8")


def load_config(path: Path) -> Config:
    return Config.from_toml(path)


def load_colors(path: Path) -> ColorSet:
    return ColorSet.from_toml(path)


# FileWatcher remains re-exported here for callers of the original API.
